require(wordcloud)
require(RColorBrewer)
datain <- read.csv("/Users/badalb/TravisCI/company-review-sentiment-analysis/src/main/resources/output/entity-set.csv", colClasses=c("character", "numeric"))
head(datain,10)
sapply(datain, class)
pal2 <- brewer.pal(8,"Dark2")
png("wordcloud.png", width=3000,height=3000)
wordcloud(datain$terms,datain$frequency, scale=c(7,0.5),min.freq=1, max.words=Inf, random.order=FALSE, rot.per=.25, colors=pal2)
dev.off()